"""Rich content for Core 30 dedicated county pages."""

CORE_COUNTIES = [
    {
        "id": "davidson",
        "slug": "davidson-county",
        "name": "Davidson County",
        "cities": "Nashville, Hermitage, Madison, Antioch, Bellevue, Old Hickory",
        "headline": "Davidson County probate families deserve calm guidance — not another crisis to manage.",
        "lead": "From downtown Nashville to Hermitage and Antioch, we help heirs navigate inherited property with court-aware compassion.",
        "meta_description": "Probate real estate help in Davidson County TN — Nashville, Hermitage, Madison, Antioch. Inherited home sales, cash offers, clean-out & Guardian Kit. (615) 669-7075.",
        "paragraphs": [
            "Davidson County is Middle Tennessee's urban heart — and when you inherit a home here, the pace can feel relentless. Metro Nashville probate timelines, vacant properties in Madison and Antioch, sibling heirs spread across the country, and a house that still needs insurance, lawn care, and decisions you are not ready to make. Most families have never done this before. You should not have to learn probate real estate while you are still grieving.",
            "Probate Guardians TN serves Davidson County heirs from our Nashville support desk and Branton Walker's field visits. We coordinate with your probate attorney on authority to sell, deliver complimentary CMAs and Net Sheets for Hermitage ranchers and Bellevue cottages alike, and present four paths on your <a href=\"/roadmap/\">Guardian Kit</a>: as-is <a href=\"/services/cash-offers-for-probate-properties/\">cash offers</a>, funded repairs, full <a href=\"/services/inherited-home-sales/\">MLS listing</a>, or retain-and-rent — always subject to court approval.",
            "Whether the property is a fixer in Antioch or a paid-off home in Old Hickory, we dispatch <a href=\"/services/house-clean-out-coordination/\">clean-out crews</a>, secure vacant homes, and run competing buyer bids through our Express Offers network. Out-of-state heirs get photo updates and weekly status — you are never the project manager of your own grief. One call to <a href=\"tel:6156697075\">(615) 669-7075</a> starts everything.",
        ],
        "challenges": [
            "Metro Nashville probate court timelines that feel faster than your family's decision-making",
            "Vacant inherited homes in Hermitage, Madison, or Antioch — insurance lapses and security worries",
            "Multiple heirs in different states with no one local to change locks or meet contractors",
            "Sibling disagreements over whether to list, take cash, or keep Mom's Nashville house",
            "Deferred maintenance on older Davidson County homes where repair costs cloud the net proceeds picture",
        ],
        "how_we_help": [
            "Same-day compassionate first call — no pressure, no investor pitch",
            "Free Guardian Kit and <a href=\"/roadmap/\">7-step Family Roadmap</a> tailored to Davidson County timelines",
            "<a href=\"/services/muniment-of-title-assistance/\">Muniment of title</a> education and vetted attorney referrals when estates may qualify",
            "Competing <a href=\"/services/cash-offers-for-probate-properties/\">cash offers</a> compared to funded-repair listing on one Net Sheet",
            "<a href=\"/services/full-service-estate-coordination/\">Full-service coordination</a> — vendors, insurance, lawn, and attorney loop-ins",
        ],
        "related_services": [
            ("Inherited Home Sales", "inherited-home-sales"),
            ("Cash Offers for Probate Properties", "cash-offers-for-probate-properties"),
            ("House Clean-Out Coordination", "house-clean-out-coordination"),
            ("Probate Real Estate Specialist", "probate-real-estate-specialist"),
        ],
        "related_counties": ["wilson-county", "sumner-county", "williamson-county"],
    },
    {
        "id": "sumner",
        "slug": "sumner-county",
        "name": "Sumner County",
        "cities": "Gallatin, Hendersonville, Portland, Westmoreland, White House",
        "headline": "Sumner County heirs — from Gallatin to the lake — should not navigate probate property alone.",
        "lead": "Gallatin court awareness, Hendersonville market expertise, and the same Guardian Kit Nashville families trust.",
        "meta_description": "Probate property help in Sumner County TN — Gallatin, Hendersonville, Portland. Inherited home sales, muniment, cash offers & clean-out. (615) 669-7075.",
        "paragraphs": [
            "Sumner County blends lake-community charm with fast-growing suburbs — and inherited property here carries its own emotional weight. The childhood home in Hendersonville, a Portland farmhouse with twenty years in the barn, a Gallatin rancher near Old Hickory Lake that siblings cannot agree on. Add Gallatin Probate Court paperwork, out-of-state heirs, and a vacant house with a lawn that keeps growing, and overwhelm arrives fast.",
            "Probate Guardians TN knows Sumner County — we support families from Portland to Westmoreland with the same system Wilson and Davidson heirs rely on. Branton Walker often meets Gallatin and Hendersonville families in person; Scott Hardesty coordinates Net Sheets, <a href=\"/services/muniment-of-title-assistance/\">muniment of title</a> timelines with your attorney, and <a href=\"/services/inherited-home-sales/\">inherited home sales</a> paths on one compassionate call.",
            "Lake homes and suburban splits alike get <a href=\"/services/house-clean-out-coordination/\">clean-out coordination</a>, funded-repair analysis, and competing <a href=\"/services/cash-offers-for-probate-properties/\">cash bids</a> when speed matters. Your free <a href=\"/roadmap/\">Guardian Kit</a> travels to your kitchen table — not a stack of forms in the mail. Call <a href=\"tel:6156697075\">(615) 669-7075</a> when you are ready; we answer with warmth, not a sales pitch.",
        ],
        "challenges": [
            "Gallatin-area probate court navigation while grieving and living out of county",
            "Hendersonville inherited homes — siblings debating list price vs. quick cash certainty",
            "Lake-community properties with contents still inside and seasonal carrying costs adding up",
            "Portland and Westmoreland vacant homes needing lockbox, lawn, and insurance coordination",
            "Family tension when one heir wants to keep the Sumner County childhood home",
        ],
        "how_we_help": [
            "Gallatin and Hendersonville CMAs with real Net Sheets — not Zillow guesses",
            "<a href=\"/services/field-team-support/\">Field team</a> walk-throughs and Guardian Kit delivery at your pace",
            "<a href=\"/services/repair-and-staging-coordination/\">Funded repairs at closing</a> for lake homes needing cosmetic refresh before listing",
            "Neutral coordinator when siblings stop speaking — weekly written status for everyone",
            "Attorney loop-ins at every milestone — we provide real estate coordination, never legal advice",
        ],
        "related_services": [
            ("Inherited Home Sales", "inherited-home-sales"),
            ("Muniment of Title Assistance", "muniment-of-title-assistance"),
            ("Field Team Support", "field-team-support"),
            ("Full-Service Estate Coordination", "full-service-estate-coordination"),
        ],
        "related_counties": ["wilson-county", "davidson-county", "rutherford-county"],
    },
    {
        "id": "wilson",
        "slug": "wilson-county",
        "name": "Wilson County",
        "cities": "Lebanon, Mt. Juliet, Watertown, Mt. Juliet lake communities",
        "headline": "Wilson County is home base — Lebanon, Mt. Juliet, and every lake road in between.",
        "lead": "Deep Wilson County court knowledge, a local vendor rolodex, and Branton Walker in the field when you need a human presence.",
        "meta_description": "Probate real estate in Wilson County TN — Lebanon, Mt. Juliet, Watertown. Inherited homes, muniment, cash offers & estate coordination. (615) 669-7075.",
        "paragraphs": [
            "Wilson County is where Probate Guardians TN feels most at home. Lebanon's courthouse rhythms, Mt. Juliet's rapid growth, Watertown's quiet streets, and lake communities where every dock holds a memory — families here inherit more than square footage. They inherit decisions: clean out the house or leave it, list in spring or take cash now, let a sibling buy out the rest or sell and divide proceeds.",
            "We built this support system for Wilson County families first. Branton Walker walks properties in Mt. Juliet and Lebanon same-week when heirs cannot face the door alone. Scott coordinates <a href=\"/services/full-service-estate-coordination/\">estate coordination</a>, dispatches <a href=\"/services/house-clean-out-coordination/\">clean-out vendors</a>, gathers <a href=\"/services/cash-offers-for-probate-properties/\">competing cash offers</a>, and aligns timelines with your attorney on <a href=\"/services/muniment-of-title-assistance/\">muniment of title</a> or formal administration — whatever fits.",
            "From a Watertown acreage to a Mt. Juliet subdivision home, you get one Project Coordinator, a complimentary Net Sheet, and the <a href=\"/roadmap/\">Family Roadmap</a> that explains every path in plain English. Wilson County heirs call us because they want compassion and competence in the same conversation. <a href=\"tel:6156697075\">(615) 669-7075</a> — we answer the same day.",
        ],
        "challenges": [
            "Mt. Juliet inherited homes with multiple heirs who disagree on timing and price",
            "Lebanon probate properties sitting vacant while court and family decisions lag",
            "Lake-community estates — contents, docks, and seasonal maintenance nobody planned for",
            "Sibling buyout questions when one heir wants to keep the Wilson County childhood home",
            "Out-of-state heirs who cannot drive to Lebanon every week for contractor meetings",
        ],
        "how_we_help": [
            "Wilson County home base — fastest field response in Lebanon and Mt. Juliet",
            "<a href=\"/services/inherited-home-sales/\">Inherited home sales</a> with list, cash, and buyout math on one page",
            "<a href=\"/services/senior-move-assistance/\">Senior move assistance</a> when care transitions precede probate",
            "Weekly status updates so every heir knows what happened — no chaotic group texts",
            "Free Guardian Kit — zero obligation to choose a path today",
        ],
        "related_services": [
            ("Probate Real Estate Specialist", "probate-real-estate-specialist"),
            ("Field Team Support", "field-team-support"),
            ("Inherited Home Sales", "inherited-home-sales"),
            ("Senior Move Assistance", "senior-move-assistance"),
        ],
        "related_counties": ["sumner-county", "rutherford-county", "davidson-county"],
    },
    {
        "id": "williamson",
        "slug": "williamson-county",
        "name": "Williamson County",
        "cities": "Franklin, Brentwood, Spring Hill, Thompson's Station, Fairview",
        "headline": "Williamson County estates deserve funded-repair analysis — and heirs deserve compassion.",
        "lead": "Franklin, Brentwood, and Spring Hill properties need real ARV math, not pressure — we deliver both.",
        "meta_description": "Probate property help in Williamson County TN — Franklin, Brentwood, Spring Hill. Funded repairs, inherited home sales & seller's agent services. (615) 669-7075.",
        "paragraphs": [
            "Williamson County sets a high bar — Franklin historic charm, Brentwood elegance, Spring Hill growth, Thompson's Station neighborhoods where every home tells a family story. Inherited property here often carries significant value, but also significant emotion. Siblings debate whether funded renovations are worth the upside. Grieving heirs worry about leaving money on the table — or spending money they do not have on repairs.",
            "Probate Guardians TN gives Williamson County families something rare: transparent numbers with a compassionate tone. We compare <a href=\"/services/repair-and-staging-coordination/\">funded repairs at closing</a> against <a href=\"/services/cash-offers-for-probate-properties/\">as-is cash</a> and full <a href=\"/services/sellers-agent-services/\">MLS listing</a> on a Net Sheet built for heirs — real proceeds after debt, commission, repairs, and carrying costs. Brentwood staging and Franklin photography are added only when ARV upside justifies the spend.",
            "High-value estates get discretion — no splashy open houses during funeral week. We coordinate <a href=\"/services/house-clean-out-coordination/\">clean-out</a>, attorney disclosures, and <a href=\"/services/full-service-estate-coordination/\">estate coordination</a> so Franklin and Brentwood families focus on family, not contractor drama. Your <a href=\"/roadmap/\">Guardian Kit</a> is free. Call <a href=\"tel:6156697075\">(615) 669-7075</a> when you want clarity without commitment.",
        ],
        "challenges": [
            "Franklin and Brentwood ARV upside vs. repair costs — siblings arguing over who pays upfront",
            "High-value listings needing probate-aware showing plans and disclosure coordination",
            "Spring Hill inherited homes split across Williamson and Maury county lines — title and court complexity",
            "Retention analysis when one heir wants to rent the Thompson's Station property for years",
            "Pressure to accept fast cash when patience and funded repairs would net significantly more",
        ],
        "how_we_help": [
            "Funded roof, HVAC, paint, and flooring — repaid only at closing, not from heir pockets",
            "<a href=\"/services/sellers-agent-services/\">Seller's agent services</a> with probate-specific marketing and offer negotiation",
            "<a href=\"/services/property-buying-and-sales/\">Property buying &amp; sales</a> guidance for buyout and hold-vs-sell decisions",
            "Professional staging and photography when the math supports it",
            "All paths subject to court approval — your attorney stays in control",
        ],
        "related_services": [
            ("Repair & Staging Coordination", "repair-and-staging-coordination"),
            ("Seller's Agent Services", "sellers-agent-services"),
            ("Inherited Home Sales", "inherited-home-sales"),
            ("Property Buying & Sales", "property-buying-and-sales"),
        ],
        "related_counties": ["davidson-county", "rutherford-county", "sumner-county"],
    },
    {
        "id": "rutherford",
        "slug": "rutherford-county",
        "name": "Rutherford County",
        "cities": "Murfreesboro, Smyrna, La Vergne, Eagleville, Lascassas",
        "headline": "Rutherford County families juggle enough — let us carry the inherited house burden.",
        "lead": "Murfreesboro, Smyrna, and La Vergne heirs get neutral Net Sheets and coordination everyone can trust.",
        "meta_description": "Probate real estate in Rutherford County TN — Murfreesboro, Smyrna, La Vergne. Cash offers, inherited home sales, clean-out & investing. (615) 669-7075.",
        "paragraphs": [
            "Rutherford County is one of the fastest-growing counties in Tennessee — and that growth complicates grief. A Murfreesboro split-level with tenant damage, a Smyrna home near the airport with siblings in three states, rural Eagleville acreage that attracts wholesaler lowballs, La Vergne properties sitting vacant while everyone waits on court. The house becomes a second job nobody applied for.",
            "Probate Guardians TN helps Rutherford County heirs replace chaos with clarity. We run neutral Net Sheets so Murfreesboro families debate numbers, not each other. Our <a href=\"/services/real-estate-investing/\">investor desk</a> delivers competing bids — not one Nashville wholesaler postcard — and we place those bids beside <a href=\"/services/inherited-home-sales/\">inherited home sales</a> and <a href=\"/services/repair-and-staging-coordination/\">funded-repair listing</a> paths on your Guardian Kit.",
            "From <a href=\"/services/house-clean-out-coordination/\">clean-out</a> in a garage full of tools to <a href=\"/services/cash-offers-for-probate-properties/\">cash offers</a> when PCS deadlines or job transfers demand speed, one Project Coordinator tracks it all with weekly updates. Explore the <a href=\"/roadmap/\">Family Roadmap</a>, then call <a href=\"tel:6156697075\">(615) 669-7075</a> — Murfreesboro to Eagleville, we are your Middle Tennessee probate property team.",
        ],
        "challenges": [
            "Murfreesboro multi-heir estates — group texts replacing decisions, tension rising weekly",
            "Smyrna properties with deferred maintenance and heirs who cannot agree on repair spend",
            "La Vergne vacant homes — utilities, insurance, and security falling through the cracks",
            "Eagleville rural acreage targeted by predatory out-of-area investor mailers",
            "Job growth bringing new heirs to Rutherford County who have never navigated Tennessee probate",
        ],
        "how_we_help": [
            "Neutral Net Sheets for multi-heir Murfreesboro and Smyrna families — everyone sees the same math",
            "48–72 hour competing <a href=\"/services/cash-offers-for-probate-properties/\">cash offer</a> cycles through Express Offers",
            "<a href=\"/services/real-estate-investing/\">Real estate investing</a> network with transparent fees for attorney review",
            "<a href=\"/services/full-service-estate-coordination/\">Estate coordination</a> — one email update replaces ten frantic texts",
            "Free CMA for every Rutherford County property — complimentary, no obligation",
        ],
        "related_services": [
            ("Cash Offers for Probate Properties", "cash-offers-for-probate-properties"),
            ("Real Estate Investing", "real-estate-investing"),
            ("Inherited Home Sales", "inherited-home-sales"),
            ("Full-Service Estate Coordination", "full-service-estate-coordination"),
        ],
        "related_counties": ["wilson-county", "williamson-county", "davidson-county"],
    },
]

OTHER_COUNTIES = [
    ("robertson", "Robertson County", "Springfield, White House, Greenbrier, Coopertown",
     "Robertson County families get the same Guardian Kit and vendor network as Nashville."),
    ("cheatham", "Cheatham County", "Ashland City, Kingston Springs, Pegram",
     "Cheatham heirs receive vacant-home insurance guidance and lawn/security coordination."),
    ("dickson", "Dickson County", "Dickson, White Bluff, Charlotte",
     "Dickson County probate properties — cash, list, or muniment paths explained plainly."),
    ("maury", "Maury County", "Columbia, Spring Hill (Maury side), Mt. Pleasant",
     "Maury County estates benefit from Columbia-market CMAs and Columbia-court awareness."),
    ("montgomery", "Montgomery County", "Clarksville, St. Bethlehem, Sango",
     "Montgomery heirs — including military families — get out-of-state heir shipping and cash options."),
    ("middle-tn", "All of Middle Tennessee", "Every county we can reach with compassion",
     "Not sure which county? One call routes you to the right court, vendors, and plan."),
]

COUNTY_BY_SLUG = {c["slug"]: c for c in CORE_COUNTIES}
COUNTY_BY_ID = {c["id"]: c for c in CORE_COUNTIES}