"""Rich service & county content for Core 30 Services page — imported by _build_pages.py."""

SERVICE_COUNTIES = [
    {
        "id": "davidson",
        "name": "Davidson County",
        "cities": "Nashville, Hermitage, Madison, Antioch, Bellevue",
        "benefit": "Nashville-area probate families get court-aware timelines without the downtown runaround.",
        "bullets": [
            "Davidson County heirs who need a calm first call — we answer the same day",
            "Coordinate vacant-home insurance while Metro Nashville probate moves forward",
            "Free CMA for Hermitage, Madison, and Antioch inherited homes",
            "Sibling buyout math when multiple heirs disagree on keeping Mom's house",
        ],
    },
    {
        "id": "sumner",
        "name": "Sumner County",
        "cities": "Gallatin, Hendersonville, Portland, Westmoreland",
        "benefit": "Helping Sumner County families turn an inherited lake house or rancher into a clear plan.",
        "bullets": [
            "Sumner County heirs navigating Gallatin Probate Court with out-of-state siblings",
            "Hendersonville estates — funded repairs vs. as-is cash on one Net Sheet",
            "Portland and Westmoreland vacant properties — lawn, lockbox, and security handled",
            "Guardian Kit walk-through at your kitchen table, not a sales pitch",
        ],
    },
    {
        "id": "wilson",
        "name": "Wilson County",
        "cities": "Lebanon, Mt. Juliet, Watertown, lake communities",
        "benefit": "Wilson County is home base — deep court knowledge and a vendor rolodex you can trust.",
        "bullets": [
            "Wilson County heirs who inherited a Mt. Juliet home and don't know where to start",
            "Lebanon probate properties — muniment, cash, or full MLS paths explained plainly",
            "Lake-community estates with contents still inside — clean-out dispatched for you",
            "Weekly status updates so Watertown families always know what's happening",
        ],
    },
    {
        "id": "rutherford",
        "name": "Rutherford County",
        "cities": "Murfreesboro, Smyrna, La Vergne, Eagleville",
        "benefit": "Rutherford estates often involve multiple heirs — we run neutral Net Sheets everyone trusts.",
        "bullets": [
            "Murfreesboro families juggling jobs, grief, and a house full of memories",
            "Smyrna heirs comparing investor cash vs. funded-repair listing upside",
            "La Vergne vacant homes — insurance, utilities, and showings coordinated",
            "Eagleville rural properties with acreage — investor network that won't lowball",
        ],
    },
    {
        "id": "williamson",
        "name": "Williamson County",
        "cities": "Franklin, Brentwood, Spring Hill, Thompson's Station",
        "benefit": "Williamson properties deserve funded-repair analysis — we present real ARV upside with compassion.",
        "bullets": [
            "Franklin heirs who want maximum net without fighting over renovation costs",
            "Brentwood estates — professional staging and photography when ARV warrants it",
            "Spring Hill inherited homes — retention analysis vs. sale proceeds for the whole family",
            "Thompson's Station probate timelines aligned with your attorney, not ours",
        ],
    },
    {
        "id": "middle-tn",
        "name": "All of Middle Tennessee",
        "cities": "Robertson, Cheatham, Dickson, Maury, Montgomery & beyond",
        "benefit": "Not sure which county? One call routes you to the right court, vendors, and plan.",
        "bullets": [
            "Clarksville military families — out-of-state heir shipping and fast cash options",
            "Columbia and Maury County estates with Columbia-market CMAs",
            "Robertson and Cheatham rural heirs — same Guardian Kit as Nashville",
            "Every path subject to court approval — we never rush you past your attorney",
        ],
    },
]

SERVICES = [
    {
        "id": "probate-specialist",
        "icon": "🛡️",
        "name": "Probate Real Estate Specialist",
        "lead": "Court-aware probate property guidance for Middle Tennessee heirs.",
        "benefit_headline": "You should not have to become a probate expert while you are still grieving.",
        "paragraphs": [
            "Losing someone you love is hard enough. Discovering you also inherited a house — with a mortgage, deferred maintenance, siblings who disagree, and a court process you have never navigated — can feel like a second wave of overwhelm. That is exactly why Probate Guardians TN exists. We are probate real estate specialists, not generalist agents chasing listings. Every conversation starts with compassion, not a pitch.",
            "We work alongside your probate attorney (never replacing them) to understand authority to sell, timeline constraints, and what the property actually needs before anyone talks numbers. You receive a complimentary CMA and Net Sheet written for heirs — real proceeds after debt, taxes, repairs, and carrying costs — so Nashville-area families in Davidson and Williamson counties, and heirs across Wilson and Sumner, can compare options on one page.",
            "Your free <a href=\"/roadmap/\">Guardian Kit</a> lays out four paths: as-is cash, funded repairs at closing, full MLS listing, or retain-and-rent — always subject to court approval. We coordinate vendors, insurance, clean-out, and competing buyers so you are never the project manager of your own grief. When you are ready — today or six months from now — we are one call away.",
        ],
        "bullets": [
            "Helping Sumner County families understand Gallatin-area probate property timelines without pressure",
            "Davidson County heirs in Hermitage and Antioch — vacant-home insurance and lockbox coordination",
            "Wilson County siblings who need neutral Net Sheets everyone can trust at the kitchen table",
            "Rutherford and Williamson estates — attorney loop-ins at every milestone, never legal advice",
            "Out-of-state heirs who cannot drive to Middle TN every week — we are your eyes on the ground",
            "Same compassionate tone as your <a href=\"/roadmap/\">Family Roadmap</a> — zero obligation to decide today",
        ],
        "related": [
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Full-Service Estate Coordination", "#estate-coordination"),
            ("Seller's Agent Services", "#sellers-agent"),
        ],
    },
    {
        "id": "inherited-home-sales",
        "icon": "🏠",
        "name": "Inherited Home Sales",
        "lead": "Sell an inherited house with clarity — as-is cash, funded repairs, or full MLS.",
        "benefit_headline": "Three real paths. One Net Sheet. No heir left guessing what they will actually receive.",
        "paragraphs": [
            "An inherited home is not just an asset — it is where holidays happened, where someone’s coffee cup still sits in the cabinet, where every sibling has a different memory and a different opinion about what to do next. We honor that emotional weight while giving your family something rare in probate: clarity.",
            "Probate Guardians TN builds a side-by-side Net Sheet for Middle Tennessee properties — list with funded repairs, as-is cash through our Express Offers network, or a sibling buyout scenario — so Murfreesboro, Franklin, and Hendersonville heirs see real dollars, not Zillow guesses. We coordinate with your attorney on court approval timelines and never push a path that does not fit your family’s grief season.",
            "Whether the house is in Lebanon, Mt. Juliet, or a quiet street in Brentwood, you get one Project Coordinator, weekly updates, and vendors dispatched from our rolodex. Explore our <a href=\"/counties/\">county guides</a> for local court flavor — then call when you are ready to compare paths without commitment.",
        ],
        "bullets": [
            "Wilson County heirs who inherited a lake home and need list-vs-cash math before spring",
            "Sumner County families comparing Portland-area investor bids on one transparent sheet",
            "Nashville-area probate properties — funded roof and HVAC repairs repaid only at closing",
            "Out-of-state siblings — we handle walk-throughs, photos, and attorney updates you cannot miss work for",
            "Sibling buyout feasibility when one heir wants to keep Mom's house in Rutherford County",
            "Every sale path clearly marked <em>subject to court approval</em> — no surprises at the courthouse",
        ],
        "related": [
            ("Cash Offers for Probate Properties", "#cash-offers-probate"),
            ("Repair & Staging Coordination", "#repair-staging"),
            ("Probate Real Estate Specialist", "#probate-specialist"),
        ],
    },
    {
        "id": "muniment-title",
        "icon": "📜",
        "name": "Muniment of Title Assistance",
        "lead": "Tennessee's faster transfer path when the estate may qualify.",
        "benefit_headline": "When muniment of title fits, families move forward faster — we help you understand if it applies.",
        "paragraphs": [
            "Tennessee offers a muniment of title path that can transfer property without a full formal administration when specific conditions are met. It sounds simpler on paper than it feels in the hallway where you are sorting through mail addressed to someone who will never open it again. We do not practice law — we educate, coordinate, and connect you with vetted probate attorneys from our rolodex who can confirm eligibility.",
            "For qualifying Middle TN estates, muniment can align property decisions sooner — retain, rent, or sell — and we provide market valuation and Net Sheet analysis so Williamson and Davidson heirs understand retain-vs-sell economics before anyone files. We align real estate timelines with your attorney’s muniment schedule so the house is not sitting vacant and uninsured while paperwork catches up.",
            "If muniment is not the right fit, we pivot without judgment to traditional probate property paths — cash, funded repairs, or MLS — all documented in your <a href=\"/roadmap/\">Guardian Kit</a>. One call to <a href=\"/counties/\">your county guide</a> and us is enough to start asking the right questions.",
        ],
        "bullets": [
            "Davidson County families asking whether muniment beats formal administration for a simple estate",
            "Wilson County heirs in Lebanon — attorney referrals plus property CMA the same week",
            "Sumner County retain-or-sell decisions when Gallatin court timelines feel opaque",
            "Education only — we loop in your lawyer before any listing or cash contract language",
            "Vacant-home insurance guidance while muniment filings are prepared",
            "Seamless handoff to <a href=\"#inherited-home-sales\">Inherited Home Sales</a> when transfer completes",
        ],
        "related": [
            ("Probate Real Estate Specialist", "#probate-specialist"),
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Full-Service Estate Coordination", "#estate-coordination"),
        ],
    },
    {
        "id": "cash-offers-probate",
        "icon": "⚡",
        "name": "Cash Offers for Probate Properties",
        "lead": "Multiple competing cash buyers — as-is, no showings, fast certainty.",
        "benefit_headline": "Competing cash bids in days — not one investor's take-it-or-leave-it number.",
        "paragraphs": [
            "Sometimes the house needs to close a chapter fast: out-of-state heirs, costly carrying months, sibling tension, or simply the emotional toll of driving past a childhood home every week. Cash can be the right answer — but one lowball investor email is not a plan. Through eXp Realty’s Express Offers network and our Middle Tennessee investor desk, Probate Guardians TN typically gathers competing as-is bids within 48–72 hours.",
            "You still see everything on a Net Sheet next to funded-repair and MLS paths — because cash is not automatically best for Franklin or Murfreesboro properties with strong ARV upside. We present numbers with compassion, coordinate court-approval language with your attorney, and handle the logistics heirs should not have to — clean-out, personal property, and final walk-throughs across Davidson, Rutherford, and Wilson counties.",
            "No showings while you are grieving. No renovation arguments. Just transparent comparison and a coordinator who answers when you text. Pair this with our <a href=\"#cleanout\">House Clean-Out</a> service and your <a href=\"/roadmap/\">Guardian Kit</a> for a complete picture.",
        ],
        "bullets": [
            "Nashville-area probate heirs overwhelmed by repairs — as-is exit without listing showings",
            "Wilson County lake homes — multiple vetted buyers, never a single wholesaler lowball",
            "Sumner County families needing certainty before school-year job transfers out of state",
            "Rutherford estates with tenant damage — cash path compared to repair-then-list on one sheet",
            "Williamson properties where speed matters more than squeezing the last 3% of ARV",
            "All offers framed <em>subject to court approval</em> — your attorney stays in control",
        ],
        "related": [
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Real Estate Investing", "#investing"),
            ("House Clean-Out Coordination", "#cleanout"),
        ],
    },
    {
        "id": "estate-coordination",
        "icon": "🧭",
        "name": "Full-Service Estate Coordination",
        "lead": "One Project Coordinator — we handle the heavy lifting so you focus on family.",
        "benefit_headline": "Stop being the accidental project manager of grief — we coordinate everything else.",
        "paragraphs": [
            "Probate scatters tasks like confetti: attorneys, insurance, utilities, lawn care, estate sales, sibling group texts, and a house that still needs to be secured. Most families have never done this before and should not have to learn on the fly while mourning. Full-Service Estate Coordination assigns you one Project Coordinator at Probate Guardians TN who owns the checklist — vendors dispatched, milestones tracked, attorney loop-ins sent.",
            "Weekly status updates mean heirs in Portland, Clarksville, or Brentwood always know what happened this week and what is scheduled next — no chasing down contractors or wondering if anyone changed the locks. We present four property paths with real Net Sheets, coordinate <a href=\"#cleanout\">clean-out</a> and <a href=\"#repair-staging\">repairs</a>, and keep the compassionate tone of your <a href=\"/roadmap/\">Family Roadmap</a> from first call to closing.",
            "This is the hub service many <a href=\"/counties/\">Middle Tennessee counties</a> families start with — one number, one coordinator, one Guardian Kit. You focus on family; we handle the house burden.",
        ],
        "bullets": [
            "Davidson County heirs juggling funeral follow-up and Metro probate deadlines simultaneously",
            "Sumner families — estate sale, haul-off, and insurance vendors from one vetted rolodex",
            "Wilson County siblings who stopped speaking — neutral coordinator everyone can email",
            "Rutherford multi-heir estates with weekly written status, not chaotic group texts",
            "Williamson high-value homes — contractor bids managed without heir arguments over paint colors",
            "Hospice and senior-living referrals through <a href=\"#senior-move\">Senior Move Assistance</a> when care transitions overlap",
        ],
        "related": [
            ("Probate Real Estate Specialist", "#probate-specialist"),
            ("House Clean-Out Coordination", "#cleanout"),
            ("Probate Real Estate Specialist — Field Team", "#probate-specialist-field"),
        ],
    },
    {
        "id": "cleanout",
        "icon": "📦",
        "name": "House Clean-Out Coordination",
        "lead": "Contents, junk, attic, garage — dispatched and tracked for you.",
        "benefit_headline": "The attic, the garage, the closets — emptied with dignity, not dumped in a panic.",
        "paragraphs": [
            "Walking through a loved one’s home after they are gone can stop you in the doorway. Every drawer is a decision. The garage is twenty years of projects. Siblings want keepsakes shipped to three states. Meanwhile the lawn is growing, the insurance company wants someone on site, and no one has the bandwidth to call ten junk haulers for quotes.",
            "Probate Guardians TN dispatches estate-sale professionals, haul-off crews, and donation partners from our Middle Tennessee rolodex — tracked by your Project Coordinator so Sumner, Wilson, and Davidson heirs are not managing dumpsters from a hotel room in another time zone. Sentimental items are inventoried and shipped; bulk removal is scheduled; $0-upfront options are explored where vendors allow.",
            "Clean-out pairs naturally with <a href=\"#cash-offers-probate\">cash offers</a>, <a href=\"#repair-staging\">repairs</a>, or <a href=\"#sellers-agent\">MLS listing</a> — we sequence work so you are not paying for work twice. See your <a href=\"/roadmap/\">Guardian Kit</a> Step 4 for how contents fit the bigger timeline.",
        ],
        "bullets": [
            "Wilson County heirs who cannot face sorting Lebanon attic boxes alone — we schedule crews at your pace",
            "Nashville-area families needing estate sale + donation receipts for probate accounting",
            "Out-of-state siblings — photo inventories and shipped keepsakes from Hendersonville homes",
            "Rutherford garages full of tools and furniture — dumpster and bulk pickup coordinated",
            "Vacant-home prep for Williamson listings — clean, secure, and show-ready without heir labor",
            "Works alongside <a href=\"#estate-coordination\">Full-Service Estate Coordination</a> or à la carte",
        ],
        "related": [
            ("Full-Service Estate Coordination", "#estate-coordination"),
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Senior Move Assistance", "#senior-move"),
        ],
    },
    {
        "id": "repair-staging",
        "icon": "🔨",
        "name": "Repair & Staging Coordination",
        "lead": "Funded repairs at closing — list at peak value without heir arguments.",
        "benefit_headline": "Fund the fixes at closing — list at peak value without heirs arguing over who writes the check.",
        "paragraphs": [
            "Many Middle Tennessee inherited homes need roof work, HVAC attention, paint, or flooring to reach full market value — but grieving families rarely have spare cash or emotional energy to manage contractors. Funded repairs at closing solve that: approved work gets done, investment is repaid from sale proceeds, and siblings stop debating who pays for the Brentwood bathroom tile.",
            "Probate Guardians TN solicits bids, schedules work, and compares the repair-then-list path against as-is cash on your Net Sheet — so Franklin and Murfreesboro heirs see net proceeds, not just a higher list price. Light staging and professional photography are added when ARV upside in Williamson or Davidson justifies the spend.",
            "Court approval and contractor liens are handled with your attorney in the loop. Explore this path beside <a href=\"#sellers-agent\">Seller's Agent Services</a> and our <a href=\"/counties/\">county market guides</a> — then call when you want real numbers, not guesswork.",
        ],
        "bullets": [
            "Williamson County heirs maximizing Franklin and Brentwood ARV without upfront renovation loans",
            "Davidson fixer-uppers in Antioch — roof and HVAC funded, repaid only when the house sells",
            "Wilson County siblings who disagree on repairs — one coordinator, three contractor bids, one decision sheet",
            "Sumner lake homes needing cosmetic refresh before spring listing season",
            "Staging and photography when <a href=\"#inherited-home-sales\">Inherited Home Sales</a> MLS path wins on math",
            "Always compared to <a href=\"#cash-offers-probate\">cash offers</a> so no one feels pushed into renovations",
        ],
        "related": [
            ("Seller's Agent Services", "#sellers-agent"),
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Cash Offers for Probate Properties", "#cash-offers-probate"),
        ],
    },
    {
        "id": "senior-move",
        "icon": "💙",
        "name": "Senior Move Assistance",
        "lead": "Care transitions and estate moves with compassion — before and during probate.",
        "benefit_headline": "Care transitions are hard enough — we lighten the house burden before probate even starts.",
        "paragraphs": [
            "Sometimes the story begins before probate: Mom needs skilled nursing, Dad’s house is too big to maintain, or hospice has been called and the family realizes no one knows what happens to the property if care lasts months. Senior Move Assistance is our compassionate bridge — movers, packing, downsizing vendors, and introductions to elder-law attorneys for Medicaid planning (always attorney-led, never from us).",
            "Probate Guardians TN helps Middle Tennessee families plan the house burden while caring for people still living. We coordinate with social workers and facility discharge planners, align timelines with eventual <a href=\"#estate-coordination\">estate coordination</a>, and keep the same warm tone Branton brings on field visits across Wilson and Sumner counties.",
            "When the time comes, your <a href=\"/roadmap/\">Guardian Kit</a> is already familiar — not a stack of surprises. Whether you are in Mt. Juliet, Gallatin, or Nashville proper, one call connects compassion with a plan.",
        ],
        "bullets": [
            "Wilson County families facing Lebanon skilled-nursing discharge with a house still full of furniture",
            "Davidson hospice families — pre-death planning so heirs are not scrambling in crisis mode",
            "Sumner heirs relocating a surviving parent to Hendersonville while selling a Portland childhood home",
            "Mover and packing referrals with items inventoried for eventual <a href=\"#cleanout\">clean-out</a>",
            "Medicaid planning introductions — vetted elder-law attorneys only, never our legal advice",
            "Branton's <a href=\"#probate-specialist-field\">field team</a> for gentle in-home walk-throughs at your pace",
        ],
        "related": [
            ("Full-Service Estate Coordination", "#estate-coordination"),
            ("House Clean-Out Coordination", "#cleanout"),
            ("Probate Real Estate Specialist — Field Team", "#probate-specialist-field"),
        ],
    },
    {
        "id": "buying-selling",
        "icon": "🔄",
        "name": "Property Buying & Sales",
        "lead": "Buy, sell, or hold inherited property — neutral guidance for the whole family.",
        "benefit_headline": "Keep it, rent it, or sell it — neutral guidance when heirs disagree on the right move.",
        "paragraphs": [
            "Not every inherited property should be sold immediately. Sometimes a Murfreesboro rental makes sense for five years; sometimes a sibling wants to buy out the others; sometimes holding until the market shifts beats a rushed cash sale. Probate Guardians TN gives neutral guidance — not a predetermined answer — with retention analysis, property management referrals, and traditional listing when maximum net is the goal.",
            "We compare hold-vs-sell economics on paper so Rutherford and Williamson families debate facts, not fear. If listing is chosen, full MLS representation pairs with funded repairs and cash backup if timelines slip. If cash wins, our <a href=\"#investing\">investor network</a> competes for your business.",
            "Every path ties back to your Net Sheet and <a href=\"/roadmap/\">Family Roadmap</a>. Explore <a href=\"/counties/\">your county</a> for local market context — then talk through what your family actually needs.",
        ],
        "bullets": [
            "Williamson heirs analyzing Franklin rental income vs. immediate sale proceeds after debt payoff",
            "Wilson County buyout math when one sibling wants to keep the Mt. Juliet childhood home",
            "Davidson multi-unit inherited properties — management referrals and cash exit backup",
            "Sumner families torn between seasonal listing and winter <a href=\"#cash-offers-probate\">cash certainty</a>",
            "Neutral facilitator when siblings in different states want opposite outcomes",
            "All outcomes <em>subject to court approval</em> and your attorney's guidance",
        ],
        "related": [
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Seller's Agent Services", "#sellers-agent"),
            ("Real Estate Investing", "#investing"),
        ],
    },
    {
        "id": "investing",
        "icon": "📈",
        "name": "Real Estate Investing",
        "lead": "Investor network for estates that need speed, certainty, or as-is exit.",
        "benefit_headline": "A vetted investor desk — multiple bids, transparent math, zero predatory wholesaling.",
        "paragraphs": [
            "Investor interest in probate property is not inherently bad — predatory single-bid behavior is. Probate Guardians TN maintains a Middle Tennessee investor desk and Express Offers relationships so estates receive multiple competing offers, not one urgent email claiming your house is worth half of reality.",
            "We wholesale-friendly timelines with court approval requirements, explain assignment language in plain English for your attorney review, and always place investor bids beside funded-repair and MLS paths on the Net Sheet. Rural Eagleville acreage, Clarksville duplexes, and dated ranchers in La Vergne all deserve the same transparent comparison.",
            "Pair investor options with <a href=\"#cash-offers-probate\">Cash Offers</a> and <a href=\"#inherited-home-sales\">Inherited Home Sales</a> education in your <a href=\"/roadmap/\">Guardian Kit</a> — then decide from strength, not exhaustion.",
        ],
        "bullets": [
            "Rutherford rural heirs tired of drive-by postcards from unknown Nashville wholesalers",
            "Montgomery and Clarksville military families needing fast as-is exit before PCS deadlines",
            "Davidson investor-owned adjacent lots — coordinated bids with probate attorney review",
            "Wilson County properties with deferred maintenance — compare investor net to repair-list net",
            "Never one lowball — typical 48–72 hour competing bid cycle through our network",
            "Full transparency on fees and assignments — your lawyer sees everything before you sign",
        ],
        "related": [
            ("Cash Offers for Probate Properties", "#cash-offers-probate"),
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Property Buying & Sales", "#buying-selling"),
        ],
    },
    {
        "id": "sellers-agent",
        "icon": "📋",
        "name": "Seller's Agent Services",
        "lead": "Full MLS representation with probate-aware marketing and disclosure.",
        "benefit_headline": "MLS representation that understands probate — disclosures, showings, and court timelines included.",
        "paragraphs": [
            "When maximum net is the goal and the family has time for a marketed sale, you deserve a seller's agent who knows probate — not one who treats your inherited home like any other listing. Probate Guardians TN handles MLS launch, probate-specific showing strategy, disclosure coordination with your attorney, and marketing that respects that the seller is grieving.",
            "Professional photography, syndication, and offer negotiation are paired with optional <a href=\"#repair-staging\">funded repairs</a> and a cash backup plan if court delays or market shifts threaten your timeline. Commission structure is explained upfront on the Net Sheet — no hidden line items for Williamson or Davidson heirs already wary of being taken advantage of.",
            "This service integrates with our <a href=\"#probate-specialist\">Probate Real Estate Specialist</a> coordination and your <a href=\"/counties/\">county guide</a> for local comp knowledge. Call when you are ready to list with compassion and competence.",
        ],
        "bullets": [
            "Franklin and Brentwood estates where ARV upside justifies funded cosmetic work at closing",
            "Nashville heirs needing probate-aware showing plans — not open houses during funeral week",
            "Sumner County listings with sibling approval workflows and weekly offer summaries",
            "Wilson County properties marketed with accurate comps from Lebanon and Mt. Juliet submarkets",
            "Commission and net proceeds spelled out before signing — aligned with <a href=\"/roadmap/\">Guardian Kit</a> Step 6",
            "Coordinated with <a href=\"#estate-coordination\">estate coordination</a> for insurance, lawn, and clean-out pre-list",
        ],
        "related": [
            ("Repair & Staging Coordination", "#repair-staging"),
            ("Inherited Home Sales", "#inherited-home-sales"),
            ("Probate Real Estate Specialist", "#probate-specialist"),
        ],
    },
    {
        "id": "probate-specialist-field",
        "icon": "🤝",
        "name": "Probate Real Estate Specialist — Field Team",
        "lead": "Branton Walker walks with families in the field — Scott coordinates the system.",
        "benefit_headline": "A real person at your door — Branton walks with you; Scott runs the system behind him.",
        "paragraphs": [
            "Some moments need a human presence, not another email thread. Branton Walker is Probate Guardians TN's field partner — same-day compassionate callbacks, property walk-throughs at your pace, and Guardian Kit delivery at the kitchen table while Scott Hardesty coordinates Net Sheets, vendors, Express Offers, and attorney loop-ins from the Nashville support desk.",
            "Families across Wilson, Sumner, Rutherford, and Davidson counties invite Branton in when the house feels too heavy to enter alone. He listens first, explains options second, and never rushes a grieving heir toward a contract. Mobile-friendly support means texts get answered, locks get changed, and photos get to out-of-state siblings without you playing project manager.",
            "This is the heart of our <a href=\"/about/\">promise</a> — compassion in the field, clarity in the system. Start with the <a href=\"/roadmap/\">Family Roadmap</a>, meet Branton when you are ready, and know <a href=\"/counties/\">your county</a> is covered.",
        ],
        "bullets": [
            "Wilson County home base — Lebanon and Mt. Juliet walk-throughs often same-week",
            "Sumner heirs in Gallatin who need a calm face before opening the childhood bedroom door",
            "Davidson families who want Guardian Kit delivery in person, not a PDF in a vacuum",
            "Rutherford siblings meeting Branton together to reduce tension before decisions",
            "Williamson estates where discretion and professionalism matter as much as comps",
            "Every field visit ties back to Scott's coordinator desk — one system, two caring partners",
        ],
        "related": [
            ("Probate Real Estate Specialist", "#probate-specialist"),
            ("Full-Service Estate Coordination", "#estate-coordination"),
            ("Senior Move Assistance", "#senior-move"),
        ],
    },
]