plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/scott/ProbateGuardian_TN/probate-landing/probate-landing"
publishOrigin = "config"
base = "/Users/scott/ProbateGuardian_TN/probate-landing"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]