-- CreateEnum
CREATE TYPE "EstateProgress" AS ENUM (
  'LETTERS_ISSUED',
  'INVENTORY_FILED',
  'NOTICE_TO_CREDITORS',
  'CREDITOR_PERIOD_ENDED',
  'DEBTS_TAXES_SETTLED',
  'FINAL_ACCOUNTING',
  'ESTATE_CLOSED'
);

-- AlterTable
ALTER TABLE "Estate" ADD COLUMN "progress" "EstateProgress" NOT NULL DEFAULT 'LETTERS_ISSUED';
